### ISSUE TITLE
multiple treatment groups

### ISSUE THREAD

**Issue by anaveenan** [wayfair/pylift#24]
I have experiment data with multiple treatment groups. How do I include this model ?

**Comment by rsyi** [comment]
You'd have to make multiple pylift.TransformedOutcome objects as well, unfortunately.

pylift seeks to maximize the lift between a treatment and another treatment (the control). We generally want to do this because it'll find splits that are more optimal for maximal lift than splitting by purity.

It's tricky to do this with multiple treatments, as you'd have to decide if you want to find the splits that maximize the difference between, for example, treatment A and control, treatment B and control, or between treatment A and treatment B. If just the first two (as should generally be the case), you can make two different models and choose the lift values that are the highest between them.
